apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: acs-demo-unauth-process-exec-kill-pod
  namespace: rhacs-operator
spec:
  policyName: Unauthorized Process Execution kill Pod # Policy name visible at ACS
  description: Kill pod if an unexpected process is executed at runtime
  categories:
    - Anomalous Activity
  lifecycleStages:
    - RUNTIME
  eventSource: DEPLOYMENT_EVENT
  scope:
    - namespace: acs-process-exec-demo
      cluster: df6a829e-7bda-4a93-9668-9489932bbef7
      label:
        key: app
        value: nginx-process-exec-demo
  severity: HIGH_SEVERITY
  enforcementActions:
    - KILL_POD_ENFORCEMENT
  policySections:
    - policyGroups:
        - fieldName: Process Name
          booleanOperator: OR
          values:
            - value: curl
            - value: cat
            - value: ls
  notifiers: 
    - email-manual
  disabled: false
  isDefault: false
