apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: acs-demo-unauth-terminal-kill-pod-labeled
  namespace: rhacs-operator
spec:
  policyName: Forbid kubectl exec (terminal access) by label # Policy name visible at ACS
  description: Block kubectl exec and oc rsh into application pods
  categories:
    - Anomalous Activity
  lifecycleStages:
    - RUNTIME
  eventSource: DEPLOYMENT_EVENT
  scope:
    - label:
        key: scope
        value: label
  exclusions:
    - name: allow-debug-label
      deployment:
        scope:
          label:
            key: debug
            value: allow
  severity: HIGH_SEVERITY
  enforcementActions:
    - KILL_POD_ENFORCEMENT
  policySections:
    - policyGroups:
        - fieldName: Process Name
          booleanOperator: OR
          values:
            - value: sh
            - value: bash
            - value: zsh
        - fieldName: Process Arguments
          values:
            - value: -i
  notifiers: 
    - email-api
  disabled: false
  isDefault: false

